name: Filtora
options:
  bundleIdPrefix: com.filtora
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
targets:
  Filtora:
    type: application
    platform: macOS
    sources:
      - path: WebsiteBlocker
        name: Filtora
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"
          - ".build"
          - "Package.swift"
          - ".gitignore"
          - ".DS_Store"
    settings:
      base:
        INFOPLIST_FILE: WebsiteBlocker/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.filtora.app
        PRODUCT_NAME: Filtora
        SWIFT_VERSION: 5.0
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES 